// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

async function main() {
  var response = await fetch("https://www.meta.ai/api/graphql/", {
        method: "POST",
        headers: Caml_option.some(new Headers({
                  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
                }))
      });
  console.log(response);
}

main();

export {
  main ,
}
/*  Not a pure module */
