name: CI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo state
        uses: actions/checkout@v4
      - name: Upload simple-pwa
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: ./simple-pwa

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4