name: CI

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo state
        uses: actions/checkout@v4
      - name: Create output folder
        run: mkdir __site
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
      - name: Build custom-checkbox
        run: |
          cd custom-checkbox
          pnpm install
          pnpm build --base /js-playground/custom-checkbox --outDir ../__site/custom-checkbox
      - name: Upload built assets
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./__site
          retention-days: 90

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
